"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { CheckCircle2, MapPin, Phone, Send } from "lucide-react";
import { useAuth } from "@/features/auth/AuthProvider";
import { bookingApi, type BookingResult } from "@/lib/booking-api";
import { venueThumbnail, type ApiVenue } from "@/lib/venue-api";

const pad = (value: number) => String(value).padStart(2, "0");
const localInput = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
const money = (value: number) => new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 }).format(value);

export function BookingRequestPage({ venue, bookingWindowStart, bookingWindowEnd }: { venue: ApiVenue; bookingWindowStart: string; bookingWindowEnd: string }) {
  const router = useRouter(); const { user, loading } = useAuth();
  const spaces = venue.spaces ?? []; const [spaceId, setSpaceId] = useState(spaces[0]?.id ?? "");
  const minimum = venue.minimumBookingMinutes; const [duration, setDuration] = useState(minimum);
  const earliest = new Date(bookingWindowStart); const latest = new Date(bookingWindowEnd);
  const [startAt, setStartAt] = useState(localInput(earliest)); const [participants, setParticipants] = useState(""); const [message, setMessage] = useState("");
  const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [result, setResult] = useState<BookingResult | null>(null);
  const space = spaces.find((item) => item.id === spaceId); const start = new Date(startAt); const end = new Date(start.getTime() + duration * 60000);
  const estimated = space ? Math.round(space.hourlyRate * duration / 60) : 0;

  async function submit(event: FormEvent) {
    event.preventDefault(); setError("");
    if (!user) { sessionStorage.setItem("indoor:open-login", "1"); sessionStorage.setItem("indoor:login-return", `/venues/${venue.id}/book`); router.push("/"); return; }
    if (!space || !Number.isFinite(start.getTime()) || start < earliest || start > latest) { setError("Select a valid space and a date/time inside the venue booking window."); return; }
    setSubmitting(true);
    try { setResult(await bookingApi.create({ venueId: venue.id, spaceId: space.id, startAt: start.toISOString(), duration, participants: participants ? Number(participants) : undefined, message: message.trim() || undefined })); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to send booking request."); }
    finally { setSubmitting(false); }
  }

  if (!spaces.length) return <main className="mx-auto min-h-[60vh] max-w-3xl px-5 py-12"><div className="rounded-2xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Booking is not available yet</h1><p className="mt-2 text-[#65756d]">This venue has no priced bookable spaces.</p><Link href={`/venues/${venue.id}`} className="mt-5 inline-block text-[#079c51] underline">Return to venue</Link></div></main>;

  if (result) return <main className="mx-auto max-w-2xl px-5 py-10"><section className="rounded-2xl border border-[#dce7e1] bg-white p-6 text-center shadow-sm sm:p-9"><CheckCircle2 className="mx-auto text-[#08ad59]" size={54} /><h1 className="mt-4 text-2xl font-bold">Request Sent!</h1><p className="mt-2 text-[#65756d]">Your booking request has been sent to <strong className="text-[#26332d]">{venue.name}</strong>.</p><div className="mx-auto mt-6 max-w-md rounded-xl bg-[#f6f9f7] p-5 text-left text-sm"><p><strong>{start.toLocaleDateString()}</strong></p><p className="mt-2">{start.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} – {end.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p><p className="mt-2">{space?.name}{participants && ` · ${participants} players`}</p><p className="mt-4 rounded-lg bg-amber-50 p-3 font-semibold text-amber-700">Status: Pending Approval</p></div><div className="mx-auto mt-6 max-w-md rounded-xl border border-[#bfe8d2] bg-[#effaf4] p-5"><Phone className="mx-auto text-[#08ad59]" /><h2 className="mt-2 font-bold">Contact Venue</h2><p className="mt-2 text-xl font-bold">{result.contact.phone}</p><a href={`tel:${result.contact.phone}`} className="mt-4 flex h-11 items-center justify-center gap-2 rounded-lg bg-[#08ad59] font-bold text-white"><Phone size={17} /> Call Now</a></div><Link href="/bookings" className="mt-5 inline-flex h-11 items-center rounded-lg border border-[#08ad59] px-6 font-semibold text-[#079c51]">View My Requests</Link></section></main>;

  const input = "mt-2 h-12 w-full rounded-lg border border-[#dbe4df] bg-white px-4 text-sm outline-none focus:border-[#08ad59]";
  // eslint-disable-next-line react-hooks/purity
  return <main className="min-h-screen bg-[#fbfcfb] px-4 py-8 sm:px-6"><div className="mx-auto max-w-[1280px]"><div className="mb-6 text-sm text-[#65756d]"><Link href="/venues">Venues</Link> <span className="mx-2">›</span> <Link href={`/venues/${venue.id}`}>{venue.name}</Link> <span className="mx-2">›</span> Request Booking</div><div className="grid gap-6 lg:grid-cols-[1.35fr_.9fr]"><form onSubmit={submit} className="rounded-2xl border border-[#dde5e1] bg-white p-5 sm:p-7"><h1 className="text-2xl font-bold">Send Booking Request</h1><p className="mt-1 text-sm text-[#65756d]">Send a request to the venue. You’ll get a response once they review it.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Court / Space<select value={spaceId} onChange={(e) => setSpaceId(e.target.value)} className={input}>{spaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Sport<input readOnly value={space?.sport ?? ""} className={`${input} bg-[#f6f9f7]`} /></label><label className="text-sm font-semibold">Date & Start Time<input required type="datetime-local" min={localInput(earliest)} max={localInput(new Date(Date.now() + venue.advanceBookingDays * 86400000))} value={startAt} onChange={(e) => setStartAt(e.target.value)} className={input} /></label><label className="text-sm font-semibold">Duration<select value={duration} onChange={(e) => setDuration(Number(e.target.value))} className={input}>{Array.from({ length: Math.floor((venue.maximumBookingMinutes - minimum) / 30) + 1 }, (_, index) => minimum + index * 30).map((minutes) => <option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label><label className="text-sm font-semibold">Participants (Optional)<input type="number" min="1" max={venue.maximumParticipants} value={participants} onChange={(e) => setParticipants(e.target.value)} className={input} placeholder={`Up to ${venue.maximumParticipants}`} /></label><label className="text-sm font-semibold sm:col-span-2">Message to venue (Optional)<textarea maxLength={500} value={message} onChange={(e) => setMessage(e.target.value)} className={`${input} h-24 py-3`} placeholder="Tell the venue anything useful…" /><span className="mt-1 block text-right text-xs font-normal text-[#7c8982]">{message.length}/500</span></label></div><div className="mt-5 rounded-lg bg-[#effaf4] p-4 text-sm text-[#23613f]">Your request will be shown as <strong>PENDING</strong>. You can contact the venue after sending the request.</div>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={submitting || loading} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#08ad59] font-bold text-white disabled:opacity-60"><Send size={18} /> {submitting ? "Sending…" : "Send Booking Request"}</button></form>
    <aside className="h-fit rounded-2xl border border-[#dde5e1] bg-white p-5 sm:p-7 lg:sticky lg:top-24"><h2 className="text-lg font-bold">Request Summary</h2><div className="mt-5 flex gap-4"><Image src={venueThumbnail(venue)} alt="" width={120} height={85} className="h-20 w-28 rounded-lg object-cover" /><div><h3 className="font-bold">{venue.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-[#65756d]"><MapPin size={14} /> {venue.area}, {venue.city}</p></div></div><dl className="mt-5 divide-y text-sm">{[["Sport", space?.sport], ["Date", Number.isFinite(start.getTime()) ? start.toLocaleDateString() : "—"], ["Time", Number.isFinite(start.getTime()) ? `${start.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} – ${end.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "—"], ["Duration", `${duration} minutes`], ["Court / Space", space?.name], ["Participants", participants ? `${participants} players` : "Not specified"]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 py-3"><dt className="text-[#65756d]">{label}</dt><dd className="text-right font-medium">{value}</dd></div>)}</dl><div className="mt-4 grid grid-cols-2 gap-4 rounded-xl bg-[#effaf4] p-4"><div><p className="text-xs text-[#65756d]">Estimated Rate</p><p className="mt-1 text-xl font-bold text-[#079c51]">{money(estimated)}</p><p className="text-xs">for {duration} minutes</p></div><div><p className="text-xs text-[#65756d]">Payment</p><p className="mt-1 font-semibold">Pay directly with the venue</p></div></div></aside></div></div></main>;
}
